spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment-automation-system
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: localhost
    port: 1025
    username: oussema
    password: oussema
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connection-timeout: 5000
        timeout: 3000
        write-timeout: 5000

application:
  security:
    jwt:
      secret-key: BF7FDBFCFC669A2729D77C7A5B325
      expiration: 868685
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account